[package]
name = "abjad-k8s"
version = "0.1.0"
edition = "2024"
authors = ["Theo Beers <tb3367@drexel.edu>"]

[dependencies]
abjad = "0.6.0"
actix-web = "4.12.1"

[dependencies.serde]
version = "1.0.228"
features = ["derive"]
